    create table currency_tbl (
        currency_cd varchar(3),
        id integer generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

insert into currency_tbl(currency_cd, name) values('INR','Indian Rupees');

insert into currency_tbl(currency_cd,name) values('USD','US Dollers');